name = "EcotoxModelFitting"
uuid = "11baf4a3-28f5-4d66-8f46-d015c3f5447c"
authors = ["SimonHansul <simonhansul@gmail.com>"]
version = "0.2.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
CSV = "0.10.15"
ComponentArrays = "0.15.25"
DataFrames = "1.7.0"
DataFramesMeta = "0.15.4"
DataStructures = "0.18.20"
Distributions = "0.25.117"
Downloads = "1.6.0"
DrWatson = "2.18.0"
JLD2 = "0.5.13"
LaTeXStrings = "1.4.0"
Latexify = "0.16.7"
Printf = "1.11.0"
ProgressMeter = "1.10.2"
StatsBase = "0.34.4"
